stages:
  - lint
  - build

lint-python:
  stage: lint
  image: python:3.12-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}-pip-cache
    paths:
      - .cache/pip
  before_script:
    - pip install --cache-dir=.cache/pip ruff
  script:
    - ruff check --output-format=gitlab .
  only:
    - main
    - merge-requests
  tags:
    - docker

build-docker:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  variables:
    IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
    DOCKER_HUB_IMAGE: vladzodchey/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "vladzodchey" --password-stdin
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --name multiarch-builder dind-context
    - docker buildx inspect --bootstrap
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME -t $DOCKER_HUB_IMAGE --push .
  only:
    - main
  tags:
    - docker