stages:
  - build

build-docker:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind'
      alias: docker
  variables:
    IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - main
  tags:
    - docker
