stages:
  - lint
  - build

lint-python:
  stage: lint
  image: ghcr.io/astral-sh/ruff:0.12.4
  script:
    - ruff check --output-format=gitlab .
  only:
    - main
    - merge-requests
  tags:
    - docker

build-docker:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  variables:
    IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
    DOCKER_HUB_IMAGE: vladzodchey/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "vladzodchey" --password-stdin
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - docker tag $IMAGE_NAME $DOCKER_HUB_IMAGE
    - docker push $DOCKER_HUB_IMAGE
  only:
    - main
  tags:
    - docker