"""Common constants for the project."""

NONE = 0
READ = 1 << 0
WRITE = 1 << 1
DELETE = 1 << 2
API = 1 << 3
ADMIN = 1 << 4
VALIDATION_MASK = READ | WRITE | DELETE | API | ADMIN

ID_CHARACTER_SET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
ID_LENGTH = 7
ID_CHARACTER_RE = rf"^[a-zA-Z0-9]{{{ID_LENGTH}}}$"
MAX_USERNAME_LENGTH = 24
MAX_PASSWORD_LENGTH = 36
MIN_USERNAME_LENGTH = 4
MIN_PASSWORD_LENGTH = 4
USERNAME_RE = rf"^[a-zA-Z0-9_\-]{{{MIN_USERNAME_LENGTH},{MAX_USERNAME_LENGTH}}}$"
PASSWORD_RE = rf"^[a-zA-Z0-9_\-\!@#$%^&*()+=.,/?<>~]{{{MIN_PASSWORD_LENGTH},{MAX_PASSWORD_LENGTH}}}$"
CONCURRENT_SESSIONS = 5
