"""Common constants for the project."""
NONE = 0
READ = 1 << 0
WRITE = 1 << 1
DELETE = 1 << 2
API = 1 << 3
ADMIN = 1 << 4
VALIDATION_MASK = (
    READ | WRITE | DELETE | API | ADMIN
)

ID_CHARACTER_SET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
ID_LENGTH = 7
MAX_USERNAME_LENGTH = 24
MAX_PASSWORD_LENGTH = 36
MIN_CRED_LENGTH = 4
CONCURRENT_SESSIONS = 5